//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by rfhutil.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MSG_FMT                     101
#define IDR_MAINFRAME                   128
#define IDR_RFHUTITYPE                  129
#define IDD_MAIN                        130
#define IDD_DATA                        131
#define IDD_RFH                         132
#define IDD_MQMD                        133
#define IDD_USR                         136
#define IDD_JMS                         137
#define IDD_PUB                         138
#define IDD_PSCR                        139
#define IDD_OTHER                       140
#define IDD_CICS                        143
#define IDD_HEXFIND                     145
#define IDD_GOTO                        146
#define IDD_DISPLAYQ                    147
#define IDD_DLQ                         148
#define IDD_SAVEMSGS                    149
#define IDD_LOADQ                       150
#define IDD_IMS                         153
#define IDD_USERID                      154
#define IDR_CONNUSER_ACCELERTOR         155
#define IDR_LOADQ_ACCELERATOR           157
#define IDR_SAVEMSGS_ACCELERATOR        158
#define IDD_MOVEQ                       159
#define IDR_MOVEQ_ACCELERATOR           160
#define IDD_V7PUBSUB                    161
#define IDD_V7PROPS                     162
#define IDD_DISP_Q                      163
#define IDD_CAPTURE_PUBS                164
#define IDD_WRITE_PUBS                  165
#define IDR_CAP_PUBS_ACCELERATOR        166
#define IDR_WRITE_PUBS_ACCELERATOR      167
#define IDC_CLOSE                       1001
#define IDC_WRITE_FILE                  1002
#define IDC_READQ                       1003
#define IDC_WRITEQ                      1004
#define IDC_EXIT                        1005
#define IDC_COPYBOOK                    1006
#define IDC_INCL_RFH                    1007
#define IDC_RFH_V1                      1008
#define IDC_RFH_NO                      1009
#define IDC_QM                          1010
#define IDC_REMOTE_QM                   1011
#define IDC_Q_NAME                      1012
#define IDC_RFH1_APP_GROUP              1013
#define IDC_ASCII                       1014
#define IDC_HEX                         1015
#define IDC_RFH_VERSION                 1016
#define IDC_BOTH                        1017
#define IDC_RFH_LENGTH                  1018
#define IDC_EBCDIC                      1019
#define IDC_RFH_ENCODING                1020
#define IDC_RFH_CHARSET                 1021
#define IDC_RFH_FLAGS                   1022
#define IDC_RFH_FORMAT                  1023
#define IDC_MSG_DOMAIN                  1024
#define IDC_MQMD_FORMAT                 1025
#define IDC_NEW_MSG_ID                  1026
#define IDC_MSG_DATA                    1027
#define IDC_RFH_CCSID                   1028
#define IDC_XML                         1029
#define IDC_MSG_ID                      1030
#define IDC_CORREL_ID                   1031
#define IDC_REPLY_QUEUE                 1032
#define IDC_RFH_V2                      1033
#define IDC_APPL_IDENTITY               1034
#define IDC_REPLY_QM                    1035
#define IDC_RFH_V2XML                   1036
#define IDC_PERSIST_YES                 1037
#define IDC_PERSIST_NO                  1038
#define IDC_PERSIST_AS_QUEUE            1039
#define IDC_MQMD_CCSID                  1040
#define IDD_MSG_TYPE                    1041
#define IDC_APPL_ORIGIN                 1042
#define IDC_COBOL                       1043
#define IDC_APPL_TYPE                   1044
#define IDC_APPL_NAME                   1045
#define IDC_FILE_NAME                   1046
#define IDC_PARSED                      1047
#define IDC_FILE_SIZE                   1048
#define IDC_RESET_IDS                   1049
#define IDC_COPYBOOK_FILE_NAME          1050
#define IDC_COPY_MSGID                  1051
#define IDC_HOST                        1052
#define IDC_PC                          1053
#define IDC_PD_PC                       1054
#define IDC_MQMD_PD_PC                  1054
#define IDC_CLEAR_DATA                  1055
#define IDC_CLEAR_ALL                   1056
#define IDC_DATA_FORMAT                 1057
#define IDC_CUSTOM1                     1058
#define IDC_NUMERIC_PC                  1059
#define IDC_CRLF                        1060
#define IDC_ERRMSG                      1061
#define IDC_BACKOUT_CNT                 1062
#define IDC_GROUP_ID                    1063
#define IDC_USER_ID                     1064
#define IDC_ID_DISP_ASCII               1065
#define IDC_ID_DISP_EBCDIC              1066
#define IDC_SEQNO                       1067
#define IDC_RFH_ENCODE_ASCII            1068
#define IDC_RFH_ENCODE_EBCDIC           1069
#define IDC_ACCOUNT_TOKEN               1070
#define IDC_RFH_PD_ENCODE_ASCII         1071
#define IDC_PUT_DATE_TIME               1072
#define IDC_RFH_PD_ENCODE_EBCDIC        1073
#define IDC_EXPIRY                      1074
#define IDC_MQMD_UNIX                   1075
#define IDC_BROWSE                      1076
#define IDC_STARTBR                     1077
#define IDC_BRNEXT                      1078
#define IDC_ENDBR                       1079
#define IDC_Q_DEPTH                     1080
#define IDC_DATA_BRNEXT                 1081
#define IDC_BIND_AS_Q                   1082
#define IDC_BIND_ON_OPEN                1083
#define IDC_BIND_NOT_FIXED              1084
#define IDC_PURGE                       1085
#define IDC_MSGTYPE                     1086
#define IDC_EDI                         1087
#define IDC_RFH_USR_DATA                1089
#define IDC_REASON1                     1090
#define IDC_PS_CONNECT_Q                1091
#define IDC_OTHER_RFH_DATA              1092
#define IDC_REGISTER                    1093
#define IDC_UNREGISTER                  1094
#define IDC_PUB_TOPIC2                  1095
#define IDC_PUB_TOPIC3                  1096
#define IDC_PUB_TOPIC4                  1097
#define IDC_PUBPERSIST                  1098
#define IDC_PUBNONPERS                  1100
#define IDC_PUB_ASPUB                   1101
#define IDC_PUBASQUEUE                  1102
#define IDC_PUB_TOPIC1                  1109
#define IDC_PUB_LOCAL                   1110
#define IDC_PUB_NEWONLY                 1111
#define IDC_PUB_ONDEMAND                1112
#define IDC_PUB_RETAIN                  1113
#define IDC_PUB_CORRELASID              1114
#define IDC_PUB_SUBPOINT                1115
#define IDC_PUB_QM                      1116
#define IDC_PUB_Q                       1117
#define IDC_PUBLISH                     1118
#define IDC_DELETE_PUB                  1119
#define IDC_PUB_PROCESS                 1120
#define IDC_PUB_CLEAR                   1121
#define IDC_REQ_PUB                     1122
#define IDC_PUB_FILTER                  1123
#define IDC_PUB_BROKER_QM               1124
#define IDC_PUB_DEREGALL                1125
#define IDC_PUB_PUBTIME                 1127
#define IDC_PUB_SEQNO                   1128
#define IDC_PUB_OTHERONLY               1130
#define IDC_INCL_MCD                    1132
#define IDC_INCL_JMS                    1133
#define IDC_INCL_USR                    1134
#define IDC_JMS_RTO                     1135
#define IDC_JMS_DST                     1136
#define IDC_JMS_PRIORITY                1139
#define IDC_JMS_EXPIRATION              1140
#define IDC_JMS_CORREL_ID               1141
#define IDC_JMS_DELIVERY_MODE           1142
#define IDC_JMS_GROUP_ID                1143
#define IDC_JMS_SEQUENCE                1144
#define IDC_JMS_TEXT                    1145
#define IDC_JMS_BYTES                   1146
#define IDC_JMS_STREAM                  1147
#define IDC_JMS_OBJECT                  1148
#define IDC_JMS_MAP                     1149
#define IDC_SAVE_REQ_DATA               1151
#define IDC_INCL_PUBSUB                 1152
#define IDC_PUB_INFORM_RETAIN           1153
#define ID_READ_FILE_ASCII              1154
#define IDC_PSCR_REPLY_OK               1156
#define IDC_PSCR_WARN                   1157
#define IDC_PSCR_ERROR                  1158
#define IDC_RESPONSE1_MESG              1160
#define IDC_REASON2                     1162
#define IDC_RESPONSE2_MESG              1163
#define IDC_PS_CONNECT_QM               1165
#define IDC_PUB_ERR_MSG                 1166
#define IDC_INCL_PSCR                   1167
#define IDC_INCL_OTHER                  1168
#define IDC_OK                          1169
#define IDC_STATIC_MESSAGE_DATA         1170
#define IDC_PD_DATA_INTEL               1172
#define IDC_MQMD_PD_HOST                1173
#define IDC_PD_DATA_HOST                1176
#define ID_READ_FILE                    1177
#define ID_READQ                        1177
#define IDC_COPYBOOK_MAIN               1178
#define IDC_MQMD_HOST                   1180
#define IDC_MQMD_PC                     1181
#define IDC_ID_DISP_HEX                 1182
#define IDC_QUEUE_TYPE                  1183
#define IDC_FEEDBACK                    1184
#define IDC_CHINESE                     1185
#define IDC_KOREAN                      1186
#define IDC_TRAD_CHINESE                1187
#define IDC_JAPAN                       1188
#define IDC_REPORT_PAN                  1189
#define IDC_REPORT_NAN                  1190
#define IDC_REPORT_EXCEPT_NONE          1191
#define IDC_REPORT_EXCEPT               1192
#define IDC_REPORT_EXCEPT_DATA          1193
#define IDC_REPORT_EXCEPT_FULL          1194
#define IDC_REPORT_EXPIRE_NONE          1195
#define IDC_INDENT                      1196
#define IDC_REPORT_EXPIRE               1197
#define IDC_ABOUT_VERSION               1198
#define IDC_REPORT_EXPIRE_DATA          1199
#define IDC_CLOSEQ                      1200
#define IDC_REPORT_EXPIRE_FULL          1201
#define IDC_REPORT_COA_NONE             1202
#define IDC_REPORT_COA                  1203
#define IDC_REPORT_COA_DATA             1204
#define IDC_REPORT_COA_FULL             1205
#define IDC_REPORT_COD_NONE             1206
#define IDC_REPORT_COD                  1207
#define IDC_REPORT_COD_DATA             1208
#define IDC_REPORT_COD_FULL             1209
#define IDC_GROUP_NO                    1210
#define IDC_GROUP_YES                   1211
#define IDC_GROUP_LAST                  1212
#define IDC_ALLOW_SEG                   1213
#define IDC_LOGICAL_ORDER               1214
#define IDC_ALL_AVAIL                   1215
#define IDC_RFH1_FLAGS                  1216
#define IDC_SEGMENT_YES                 1220
#define IDC_SEGMENT_LAST                1221
#define IDC_OFFSET                      1224
#define IDC_LAST_IN_GROUP               1225
#define IDC_PUB_ISRETAINED              1226
#define IDC_SET_USERID                  1227
#define IDC_PSCR_OTHER                  1231
#define IDC_REG_PUB                     1233
#define IDC_DEREG_PUB                   1234
#define IDC_PUB_SUB_NAME                1235
#define IDC_PUB_SUB_IDENTITY            1236
#define IDC_PUB_SUB_DATA                1237
#define IDC_RFH_BOTH                    1238
#define IDC_INCL_V1_MCD                 1239
#define IDC_INCL_V1_PUBSUB              1240
#define IDC_RFH1_FORMAT_NAME            1241
#define IDC_RFH1_ENCODE_ASCII           1242
#define IDC_RFH1_ENCODE_EBCDIC          1243
#define IDC_RFH1_PD_ENCODE_PC           1245
#define IDC_RFH1_PD_ENCODE_HOST         1246
#define IDC_RFH1_FORMAT                 1247
#define IDC_RFH1_CHARSET                1248
#define IDC_MSG_SET                     1249
#define IDC_MSG_TYPE                    1250
#define IDC_MSG_FMT                     1251
#define IDC_RFH1_LENGTH                 1253
#define IDC_PUB_FULL_RESP               1254
#define IDC_PUB_JOIN_SHARED             1255
#define IDC_PUB_JOIN_EXCL               1256
#define IDC_PUB_ADD_NAME                1257
#define IDC_PUB_NOALTER                 1258
#define IDC_PUB_VAR_USER                1259
#define IDC_PUB_LOCKED                  1260
#define IDC_PUB_DIRECT_REQ              1261
#define IDC_PUB_DUPS_OK                 1262
#define IDC_PUB_INCL_STREAM_NAME        1263
#define IDC_PUB_LEAVE_ONLY              1264
#define IDC_PUB_NO_REG                  1265
#define IDC_GET_BY_CORRELID             1266
#define IDC_REPORT_PASS_CORRELID        1267
#define IDC_PUB_ANON                    1268
#define IDC_INCL_V1_RESP                1269
#define IDC_PSCR_ERROR_ID               1270
#define IDC_PSCR_ERROR_POS              1271
#define IDC_PSCR_PARM_ID                1272
#define IDC_PSCR_USER_ID                1273
#define IDC_JMS_TIMESTAMP               1274
#define IDC_JMS_NONE                    1275
#define IDC_JMS_USER_DEF                1276
#define IDC_PUB_OTHER                   1277
#define IDC_LOAD_QUEUE_NAMES            1278
#define IDC_CIH_NONE                    1279
#define IDC_V1                          1280
#define IDC_CIH_V1                      1280
#define IDC_V2                          1281
#define IDC_CIH_V2                      1281
#define IDC_CIH_FACILITY                1282
#define IDC_CIH_UOW_ONLY                1283
#define IDC_CIH_UOW_CONT                1284
#define IDC_CIH_UOW_FIRST               1285
#define IDC_CIH_UOW_MIDDLE              1286
#define IDC_CIH_UOW_LAST                1287
#define IDC_CIH_UOW_COMMIT              1288
#define IDC_CIH_UOW_ROLLBACK            1289
#define IDC_CIH_SC_NONE                 1290
#define IDC_CIH_SC_START                1291
#define IDC_CIH_SC_DATA                 1292
#define IDC_CIH_SC_TERM                 1293
#define IDC_CIH_END_NOSYNC              1294
#define IDC_CIH_END_COMMIT              1295
#define IDC_CIH_END_BACKOUT             1296
#define IDC_CIH_END_ENDTASK             1297
#define IDC_CIH_CONVERSATIONAL          1298
#define IDC_CIH_FORMAT                  1299
#define IDC_CIH_PROGRAM                 1300
#define IDC_CIH_NEXT_TRANID             1301
#define IDC_CIH_RETURN_CODE             1302
#define IDC_CIH_COMP_CODE               1303
#define IDC_CIH_REASON                  1304
#define IDC_CIH_CANCEL_CODE             1305
#define IDC_CIH_CURSOR_POS              1306
#define IDC_CIH_ERROR_OFFSET            1307
#define IDC_CIH_FACILITY_LIKE           1308
#define IDC_CIH_AID                     1309
#define IDC_CIH_TRANS_ID                1310
#define IDC_CIH_REMOTE_SYS              1311
#define IDC_CIH_REMOTE_TRAN             1312
#define IDC_CIH_REPLY_FORMAT            1313
#define IDC_CIH_CODEPAGE                1314
#define IDC_CIH_FLAGS                   1315
#define IDC_CIH_WAIT_INTERVAL           1316
#define IDC_CIH_LINK_PROG               1318
#define IDC_CIH_LINK_TRAN               1319
#define IDC_CIH_DATA_LENGTH             1320
#define IDC_CIH_ABEND_CODE              1321
#define IDC_CIH_AUTHENTICATOR           1322
#define IDC_CIH_KEEP_TIME               1323
#define IDC_CIH_INPUT_ITEM              1324
#define IDC_CIH_INT_ENCODE_PC           1325
#define IDC_CIH_INT_ENCODE_HOST         1326
#define IDC_CIH_PD_ENCODE_PC            1328
#define IDC_CIH_PD_ENCODE_HOST          1329
#define IDC_CIH_FUNCTION                1334
#define IDC_DATA_VALIDATE               1335
#define IDC_CIH_ADS_SEND                1336
#define IDC_CIH_ADS_RECEIVE             1337
#define IDC_CIH_ADS_MSG_FORMAT          1338
#define IDC_MQMD_ORIG_LEN               1344
#define IDC_MQMD_FEEDBACK               1345
#define IDC_MQMD_PRIOTITY               1346
#define IDC_SET_ALL                     1349
#define IDC_HEX_VALUE                   1351
#define IDC_HEX_EDIT_ERRMSG             1352
#define IDC_GOTO_OFFSET                 1353
#define IDC_GOTO_ERRMSG                 1354
#define IDC_GOTO_LABEL                  1355
#define IDC_HEXFIND_UP                  1356
#define IDC_HEXFIND_DOWN                1357
#define IDC_BRPREV                      1358
#define IDC_DATA_BRPREV                 1359
#define IDC_DISPLAYQ_MSGS               1360
#define IDC_DISPLAYQ_READ               1361
#define IDC_DISPLAYQ_BROWSE             1362
#define IDC_MAIN_DISPLAYQ               1363
#define IDC_GET_MSG_ID                  1365
#define IDC_DISPLAYQ_STARTBR            1366
#define IDC_DISPLAYQ_HEADER             1367
#define IDC_DLQ_INCL_YES                1368
#define IDC_DLQ_INCL_NO                 1369
#define IDC_DLQ_REASON                  1370
#define IDC_DLQ_ORIG_QM                 1371
#define IDC_DLQ_ORIG_Q                  1372
#define IDC_DLQ_FORMAT                  1373
#define IDC_DLQ_CODEPAGE                1374
#define IDC_DLQ_PUT_APPL_NAME           1375
#define IDC_DLQ_DATE_TIME               1376
#define IDC_DLQ_PUT_APPL_TYPE           1377
#define IDC_DLQ_RESEND                  1378
#define IDC_DLQ_PC                      1379
#define IDC_DLQ_HOST                    1380
#define IDC_DLQ_PD_PC                   1382
#define IDC_DLQ_PD_HOST                 1383
#define IDC_DLQ_PREP_RESEND             1384
#define IDC_MAIN_SAVEQ                  1385
#define IDC_SAVEMSGS_FILENAME           1386
#define IDC_SAVEMSGS_BROWSE             1387
#define IDC_SAVEMSGS_ONEFILE            1388
#define IDC_SAVEMSGS_FILE_PER_MSG       1389
#define IDC_SAVEMSGS_DELIMITER          1390
#define IDC_DISPMSGS_DELIM_CHAR         1391
#define IDC_DISPMSGS_DELIM_HEX          1392
#define IDC_DISPMSGS_END_COUNT          1393
#define IDC_DISPMSGS_START              1394
#define IDC_DISPMSGS_REM_NO             1395
#define IDC_DISPMSGS_REM_YES            1396
#define IDC_SAVEMSGS_INCL_MQMD          1397
#define IDC_SAVEMSGS_INCL_HEADERS       1398
#define IDC_LOADQ_REMOVE_MQMD           1399
#define IDC_LOADQ_REM_HEADERS           1400
#define IDC_LOADQ_DELIMITER             1401
#define IDC_LOADQ_DELIM_CHAR            1402
#define IDC_LOADQ_DELIM_HEX             1403
#define IDC_LOADQ_FILE_PER_MSG          1404
#define IDC_LOADQ_ONEFILE               1405
#define IDC_LOADQ_FILENAME              1406
#define IDC_LOADQ_BROWSE                1407
#define IDC_MAIN_LOADQ                  1408
#define IDC_LOADQ_MAX_COUNT             1409
#define IDC_LOADQ_PERSISTENT            1410
#define IDC_LOADQ_FORMAT                1411
#define IDC_LOADQ_CCSID                 1412
#define IDC_LOADQ_ENCODING              1413
#define IDC_LOADQ_USE_SET_ALL           1414
#define IDC_SAVEMSGS_ERROR_MSG          1415
#define IDC_DISPLAYQ_READQ              1416
#define IDC_DISPLAYQ_START_BROWSE       1417
#define IDC_DISPLAYQ_BROWSE_MSG         1418
#define IDC_LOADQ_NEW_MSGID             1419
#define IDC_LOADQ_START_MSG             1420
#define IDC_MAIN_CONVERT                1421
#define IDC_SEGMENT_ALLOWED             1422
#define IDC_COMPLETE_MSG                1423
#define IDC_IIH_PD_ENCODE_PC            1424
#define IDC_IIH_PD_ENCODE_HOST          1425
#define IDC_IIH_INT_ENCODE_PC           1426
#define IDC_IIH_INT_ENCODE_HOST         1427
#define IDC_IIH_FORMAT                  1429
#define IDC_IIH_MAP_NAME                1430
#define IDC_IIH_REPLY_FORMAT            1431
#define IDC_IIH_LTERM                   1432
#define IDC_IIH_AUTHENTICATOR           1433
#define IDC_IIH_TRANS_ID                1434
#define IDC_IIH_NO_CONVERSATION         1435
#define IDC_IIH_IN_CONVERSATION         1436
#define IDC_IIH_ARCHITECTED             1437
#define IDC_IIH_COMMIT_FIRST            1438
#define IDC_IIH_SEND_FIRST              1439
#define IDC_IIH_SEC_CHECK               1440
#define IDC_IIH_SEC_FULL                1441
#define IDC_IIH_INCLUDE_HEADER          1442
#define IDC_IIH_PASS_EXPIRATION         1443
#define IDC_IIH_NO_REPLY_FORMAT         1444
#define IDC_IIH_CODEPAGE                1445
#define IDC_DLQ_INCLUDE_HEADER          1451
#define IDC_IIH_ADD_LENGTH              1452
#define IDC_CONN_USERID                 1453
#define IDC_CONN_PASSWORD               1454
#define IDC_CONN_RESET                  1455
#define IDC_SET_CONN_USER               1456
#define IDC_ALT_USERID                  1457
#define IDC_REPORT_PASS_MSGID           1458
#define IDC_REPORT_DISCARD              1460
#define IDC_REPORT_ACTIVITY             1461
#define IDC_REPORT_EXPIRY_DISCARD       1462
#define IDC_RFH1_INCLUDE_HEADER         1463
#define IDC_RFH2_INCLUDE_HEADER         1464
#define IDC_GET_BY_GROUP_ID             1465
#define IDC_CONN_USE_SSL                1466
#define IDC_CONN_SSL_CIPHER             1468
#define IDC_CONN_SSL_CIPHER_LABEL       1469
#define IDC_CONN_VALIDATE_CLIENT        1470
#define IDC_CONN_SSL_KEYR               1471
#define IDC_CONN_BROWSE                 1472
#define IDC_CONN_STORE_LOC_LABEL        1473
#define IDC_CONN_SSL_RESET_COUNT        1474
#define IDC_CONN_SSL_RESET_COUNT_LABEL  1475
#define IDC_SAVEMSGS_END_COUNT          1477
#define IDC_SAVEMSGS_START              1478
#define IDC_SAVEMSGS_REM_YES            1479
#define IDC_SAVEMSGS_REM_NO             1480
#define IDC_SAVEMSGS_DELIM_HEX          1481
#define IDC_SAVEMSGS_DELIM_CHAR         1482
#define IDC_MOVEQ_PASS_ALL              1484
#define IDC_NEW_CORREL_ID               1485
#define IDC_EXIT_BUTTON                 1487
#define IDC_MOVEQ_QUEUE_NAME            1488
#define IDC_MOVEQ_START_MSG             1489
#define IDC_MOVEQ_MAX_COUNT             1490
#define IDC_MOVEQ_REMOVE_DLQ            1491
#define IDC_MAIN_MOVEQ                  1493
#define IDC_CONN_SECURITY_EXIT          1494
#define IDC_CONN_SECURITY_DATA          1495
#define IDC_CONN_SECURITY_EXIT_LABEL    1496
#define IDC_CONN_SECURITY_DATA_LABEL    1497
#define IDC_CONN_LOCAL_ADDRESS_LABEL    1498
#define IDC_CONN_LOCAL_ADDRESS          1499
#define IDC_LOADQ_ERROR_MESSAGE         1500
#define IDC_MAIN_FILTER_LABEL           1503
#define IDC_MAIN_FILTER                 1504
#define IDC_LOADQ_PROP_DELIM            1508
#define IDC_PROPS_USER_PROPERTIES       1509
#define IDC_PS_QM                       1511
#define IDC_PS_BROKER_QM                1513
#define IDC_PS_SUBNAME                  1514
#define IDC_PS_SUBSCRIBE                1515
#define IDC_PS_PUBLISH                  1516
#define IDC_PS_GET                      1517
#define IDC_PS_CLOSEQ                   1518
#define IDC_PS_GET_TOPICS               1519
#define IDC_PS_GET_SUBS                 1520
#define IDC_PS_TOPIC                    1521
#define IDC_PS_DURABLE                  1522
#define IDC_PS_REMOVE                   1523
#define IDC_PS_ERRORMSGS                1524
#define IDC_PS_MANAGED                  1525
#define IDC_PS_RESUME                   1526
#define IDC_PS_WAIT_INTERVAL            1527
#define IDC_PS_RETAIN                   1528
#define IDC_PS_QUEUE_NAME               1529
#define IDC_PS_LOCAL                    1530
#define IDC_PS_NOT_OWN                  1531
#define IDC_PS_SUPPRESS_REPLY           1532
#define IDC_PS_ON_DEMAND                1533
#define IDC_PS_NEW_ONLY                 1534
#define IDC_PS_TOPIC_NAME               1535
#define IDC_PS_REQ_PUB                  1536
#define IDC_PS_NEW_CORREL_ID            1537
#define IDC_PS_SUB_LEVEL                1538
#define IDC_PS_PRIORITY                 1539
#define IDC_PS_GROUP_SUB                1541
#define IDC_PS_CORREL_ID                1542
#define IDC_PS_EXPIRY                   1543
#define IDC_PS_SET_CORREL_ID            1544
#define IDC_PS_CORREL_ASCII             1545
#define IDC_PS_CORREL_HEX               1546
#define IDC_PS_WILDCARD_TOPIC           1547
#define IDC_PS_WILDCARD_CHAR            1548
#define IDC_PS_USER_DATA                1549
#define IDC_PS_CLEAR                    1550
#define IDC_PS_ANY_USERID               1551
#define IDC_RFH_FROM_USER               1552
#define IDC_PROPS_MOVE_RFH_USR          1553
#define IDC_PS_IS_RETAINED              1554
#define IDC_PS_APPL_IDENT               1555
#define IDC_PS_ACCT_TOKEN               1556
#define IDC_PS_ALTER_SUB                1557
#define IDC_PS_SET_IDENT                1558
#define IDC_MAIN_PROPS_NONE             1559
#define IDC_MAIN_PROPS_YES              1560
#define IDC_MAIN_PROPS_RFH2             1561
#define IDC_MAIN_PROPS_AS_QUEUE         1562
#define IDC_SAVEMSGS_PROP_DELIM         1563
#define IDC_LOADQ_IGNORE_PROPS          1564
#define IDC_MAIN_PROPS_COMPAT           1565
#define IDC_PS_SELECTION                1566
#define IDC_THAI                        1567
#define IDC_JSON                        1568
#define IDC_FIX                         1569
#define IDC_PS_WARN_NO_PUBS             1570
#define IDC_DISPQ_MSGS                  1571
#define IDC_DISPQ_READQ                 1572
#define IDC_DISPQ_BROWSEQ               1573
#define IDC_DISPQ_START_BROWSE          1574
#define IDC_DISPQ_CLOSE                 1575
#define IDC_MAIN_FILE_CODEPAGE          1576
#define IDC_USE_CSP                     1578
#define IDC_SAVEMSGS_APPEND             1579
#define IDC_STATIC_STARTMSG             1580
#define IDC_STATIC_MAXCOUNT             1581
#define IDC_STATIC_REMOVE_QUEUE         1582
#define IDC_STATIC_MANYFILES            1583
#define IDC_PS_SAVE_MSGS                1584
#define IDC_CAPTURE_BROWSE              1585
#define IDC_CAPTURE_DELIM_CHAR          1586
#define IDC_CAPTURE_DELIM_HEX           1587
#define IDC_CAPTURE_DELIMITER           1588
#define IDC_CAPTURE_PROP_DELIM          1589
#define IDC_CAPTURE_INCL_MQMD           1590
#define IDC_CAPTURE_INCL_HEADERS        1591
#define IDC_CAPTURE_APPEND              1592
#define IDC_CAPTURE_END_COUNT           1593
#define IDC_CAPTURE                     1594
#define IDC_CAPTURE_FILENAME            1595
#define IDC_CAPTURE_STOP                1596
#define IDC_CAPTURE_MAX_WAIT            1597
#define IDC_CAPTURE_ERROR_MSG           1598
#define IDC_PS_WRITE_MSGS               1599
#define IDC_WRITEPUBS_FILENAME          1600
#define IDC_WRITEPUBS_BROWSE            1601
#define IDC_WRITEPUBS_DELIM_CHAR        1602
#define IDC_WRITEPUBS_DELIM_HEX         1603
#define IDC_WRITEPUBS_DELIMITER         1604
#define IDC_WRITEPUBS_PROP_DELIM        1605
#define IDC_WRITEPUBS_END_COUNT         1606
#define IDC_WRITEPUBS_WAIT              1607
#define IDC_WRITEPUBS_ERROR_MSG         1608
#define IDC_WRITEPUBS_PUB_MSGS          1609
#define IDC_WRITEPUBS_STOP_PUB          1610
#define IDC_WRITEPUBS_BATCHSIZE         1611
#define IDC_WRITEPUBS_WRITE_ONCE        1612
#define IDC_WRITEPUBS_NEW_MSGID         1613
#define IDC_WRITEPUBS_NEW_CORRELID      1614
#define IDC_WRITEPUBS_USE_MQMD          1615
#define IDC_LOADQ_WAIT_TIME             1616
#define IDC_LOADQ_BATCH_SIZE            1617
#define IDC_CAPTURE_INCL_PROPS          1618
#define IDC_CAPTURE_INCL_TOPIC          1619
#define IDC_WRITEPUBS_USE_TOPIC         1620
#define IDC_WRITEPUBS_USE_PROPS         1621
#define IDC_LOADQ_WRITE_ONCE            1622
#define IDC_WRITEPUBS_WARN_NO_MATCH     1623
#define IDC_BIND_GROUP                  1624
#define IDC_PS_NO_MULTICAST             1625
#define IDC_MQMD_FLOAT_PC               1627
#define IDC_MQMD_FLOAT_UNIX             1628
#define IDC_MQMD_FLOAT_390              1629
#define IDC_MQMD_FLOAT_TNS              1630
#define IDC_RFH_ENCODE_FLOAT_PC         1631
#define IDC_RFH_ENCODE_FLOAT_UNIX       1632
#define IDC_RFH_ENCODE_FLOAT_390        1633
#define IDC_RFH_ENCODE_FLOAT_TNS        1634
#define IDC_CIH_FLOAT_ENCODE_PC         1635
#define IDC_CIH_FLOAT_ENCODE_HOST       1636
#define IDC_CIH_FLOAT_ENCODE_390        1637
#define IDC_CIH_FLOAT_ENCODE_TNS        1638
#define IDC_DLQ_FLOAT_PC                1639
#define IDC_DLQ_FLOAT_HOST              1640
#define IDC_DLQ_FLOAT_390               1641
#define IDC_DLQ_FLOAT_TNS               1642
#define IDC_IIH_FLOAT_ENCODE_PC         1643
#define IDC_IIH_FLOAT_ENCODE_HOST       1644
#define IDC_IIH_FLOAT_ENCODE_390        1645
#define IDC_IIH_FLOAT_ENCODE_TNS        1646
#define IDC_RFH1_FLOAT_ENCODE_PC        1647
#define IDC_RFH1_FLOAT_ENCODE_HOST      1648
#define IDC_RFH1_FLOAT_ENCODE_390       1649
#define IDC_RFH1_FLOAT_ENCODE_TNS       1650
#define IDC_CLOSE_NONE                  1651
#define IDC_CLOSE_DELETE                1652
#define IDC_CLOSE_PURGE                 1653
#define IDC_RUSSIAN                     1654
#define IDC_SPIN1                       1655
#define IDC_SAVEMSGS_MAXFILESIZE        1658
#define IDC_LOADQ_SINGLE_FILE           1659
#define IDC_DATA_BOM                    1661
#define IDC_MOVEQ_REMOVE_DLQ_KEY        32665
#define IDC_MOVEQ_PASS_ALL_KEY          32666
#define IDM_READ_NOCRLF                 32771
#define IDM_READ_UNIX                   32772
#define IDM_READ_EBCDIC                 32773
#define IDM_READ_DATAONLY               32774
#define IDM_READ_IGNORE_HEADER          32775
#define IDM_WRITE_DATAONLY              32776
#define IDM_READ_SAVE_RFH               32777
#define IDM_VIEW_SYSTEM_QUEUES          32778
#define IDM_SAVE_MSG_ID                 32779
#define IDM_SAVE_CORREL_ID              32780
#define IDM_SAVE_GROUP_ID               32781
#define IDM_RESTORE_MSG_ID              32782
#define IDM_RESTORE_CORREL_ID           32783
#define IDM_RESTORE_GROUP_ID            32784
#define IDM_COPY_MSG_ID                 32785
#define IDM_RESTORE_CICS_FACILITY       32787
#define IDM_FILE_READ                   32788
#define IDM_FILE_WRITE                  32789
#define IDC_OPEN                        32790
#define IDC_MENU_INCLUDE_MQMD           32791
#define IDC_MENU_IGNORE_MQMD            32792
#define IDM_INCLUDE_MQMD                32793
#define IDM_READ_IGNORE_MQMD            32794
#define IDM_WRITE_INCLUDE_MQMD          32795
#define IDM_SEARCH_FIND                 32796
#define IDM_SEARCH_NEXT                 32797
#define IDM_SEARCH_FIND_HEX             32798
#define IDM_SEARCH_GOTO                 32799
#define IDM_VIEW_CLUSTER                32800
#define ID_BRNEXT                       32801
#define ID_BRPREV                       32802
#define IDM_RESTORE_TRANS_ID            32803
#define IDM_SAVE_IMS_TRANSID            32804
#define ID_EDIT_TOP                     32805
#define ID_EDIT_BOTTOM                  32806
#define IDM_MQ_MQCONN                   32807
#define IDM_MQ_MQDISC                   32808
#define IDM_MQ_MQOPEN_GET               32809
#define IBM_MQ_MQOPEN_PUT               32811
#define IBM_MQ_MQCLOSE                  32812
#define IDM_MQ_MQOPEN_PUT               32813
#define IDM_MQ_MQCLOSE                  32814
#define IDM_MQ_ENDBR                    32815
#define IDM_MQ_MQOPEN_BROWSE            32816
#define ID_BROWSEQ                      32817
#define ID_DISPLAYQ                     32818
#define ID_PURGEQ                       32819
#define ID_LOADNAMES                    32820
#define ID_SET_CONN_USER                32821
#define ID_CLEARALL                     32822
#define ID_CLOSEQ                       32823
#define ID_LOADQ                        32824
#define ID_STARTBR                      32825
#define ID_WRITEQ                       32826
#define ID_SAVEQ                        32827
#define ID_ENDBROWSE                    32828
#define ID_COPYBOOK                     32829
#define ID_RESETIDS                     32830
#define ID_COPYMSGID2CORRELID           32831
#define IDM_NEXT_TAB                    32832
#define IDM_PREV_TAB                    32833
#define IDC_CONN_USE_SSL_KEY            32834
#define IDC_CONN_VALIDATE_KEY           32835
#define IDC_LOADQ_FILE_PER_MSG_KEY      32836
#define IDC_LOADQ_ONEFILE_KEY           32837
#define IDC_LOADQ_DELIM_CHAR_KEY        32839
#define IDC_LOADQ_DELIM_HEX_KEY         32840
#define IDC_LOADQ_PERSISTENT_KEY        32841
#define IDC_LOADQ_NEW_MSGID_KEY         32842
#define IDC_LOADQ_USE_SET_ALL_KEY       32843
#define IDC_LOADQ_REM_HEADERS_KEY       32844
#define IDC_LOADQ_REMOVE_MQMD_KEY       32845
#define IDC_SAVEMSGS_ONEFILE_KEY        32846
#define IDC_SAVEMSGS_BROWSE_KEY         32847
#define IDC_SAVEMSGS_FILE_PER_MSG_KEY   32848
#define IDC_SAVEMSGS_DELIM_CHAR_KEY     32849
#define IDC_SAVEMSGS_DELIM_HEX_KEY      32850
#define IDC_SAVEMSGS_REM_NO_KEY         32851
#define IDC_SAVEMSGS_REM_YES_KEY        32852
#define IDC_SAVEMSGS_INCL_MQMD_KEY      32853
#define IDC_SAVEMSGS_INCL_HEADERS_KEY   32854
#define ID_TRAD_CHINESE                 32855
#define ID_SIMP_CHINESE                 32856
#define ID_ASCII                        32857
#define ID_EBCDIC                       32858
#define ID_KOREAN                       32859
#define IDM_PS_GET_MSG                  32860
#define IDM_PS_GET_SUBS                 32861
#define IDM_PS_PUBLISH                  32862
#define IDM_PS_RESUME                   32863
#define IDM_PS_CLEAR_ALL                32864
#define IDM_FIX                         32868
#define IDM_THAI                        32869
#define IDM_JSON                        32870
#define IDM_SAVE_CICS_FACILITY          32871
#define ID_PS_WRITE_MSGS                32872
#define IDC_CAPTURE_DELIM_CHAR_KEY      32873
#define IDC_CAPTURE_DELIM_HEX_KEY       32874
#define IDC_CAPTURE_INCL_MQMD_KEY       32875
#define IDC_CAPTURE_INCL_HEADERS_KEY    32876
#define IDC_CAPTURE_APPEND_KEY          32877
#define IDC_CAPTURE_INCL_PROPS_KEY      32878
#define IDC_CAPTURE_INCL_TOPIC_KEY      32879
#define IDC_CAPTURE_KEY                 32880
#define IDC_CAPTURE_STOP_KEY            32881
#define IDC_PS_WRITE_MSGS_KEY           32882
#define IDC_WRITEPUBS_DELIM_CHAR_KEY    32883
#define IDC_WRITEPUBS_DELIM_HEX_KEY     32884
#define IDC_WRITEPUBS_PUB_MSGS_KEY      32885
#define IDC_WRITEPUBS_STOP_PUB_KEY      32886
#define IDC_WRITEPUBS_WRITE_ONCE_KEY    32887
#define IDC_WRITEPUBS_NEW_MSGID_KEY     32888
#define IDC_WRITEPUBS_NEW_CORRELID_KEY  32889
#define IDC_WRITEPUBS_USE_MQMD_KEY      32890
#define IDC_WRITEPUBS_USE_TOPIC_KEY     32891
#define IDC_WRITEPUBS_USE_PROPS_KEY     32892
#define IDC_WRITEPUBS_WRITE_KEY         32893
#define IDC_WRITEPUBS_STOP_KEY          32894
#define IDC_LOADQ_WRITE_ONCE_KEY        32895
#define ID_FILE_OPEN_ASCII              57602
#define ID_INDICATOR_FILE               59142
#define ID_INDICATOR_ERR                59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32897
#define _APS_NEXT_CONTROL_VALUE         1662
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
